jwt:
  secretKey: rttswghjqkfsghajratyrsatysratyartyatry


spring:
  application:
    name: api-gateway
  server:
    port: 8080

  #api gateway config
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2
#            - RedirectTo=302,http://codingshuttle.com
            - name: LoggingOrdersFilter
<<<<<<< HEAD
            - name: Authentication
              args:
                isEnabled: false
            - name: Authorization
              args:
                allowedRoles: ADMIN,SUPER_ADMIN
=======
>>>>>>> b91c71d122dddd8ecd5294fdd98071d9788cf24e
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Custom-Header,Richa
            - name: Authentication

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true